#!/usr/bin/env bash

set -euo pipefail

readonly SCRIPT_DIR=$(dirname "$0")
readonly LOG_FOLDER_KEY=logFolder
readonly LOG_FILE=handler.log
readonly HANDLER_ENV_PATH="${SCRIPT_DIR}/../HandlerEnvironment.json"
readonly HANDLER_ENV=$(cat $HANDLER_ENV_PATH) # If file is missing, this will come out blank

readonly ARCHITECTURE=$( [[ "$(uname -p)" == "unknown" ]] && echo "$(uname -m)" || echo "$(uname -p)" ) # ternary operator
HANDLER_BIN="custom-script-extension"
if [ $ARCHITECTURE == "arm64" ] || [ $ARCHITECTURE == "aarch64" ]; then
    HANDLER_BIN="custom-script-extension-arm64"
fi

LOG_DIR="/var/log/azure/custom-script"
if [[ "$HANDLER_ENV" == *"$LOG_FOLDER_KEY"* ]]; then
       tmp=${HANDLER_ENV#*$LOG_FOLDER_KEY\": \"}
       LOG_DIR=${tmp%%\"\,*}
       unset tmp
fi

echo "Placing logs in directory $LOG_DIR"

# status_file returns the .status file path we are supposed to write
# by determining the highest sequence number from ./config/*.settings files.
status_file_path() {
        # normally we would need to find this config_dir by parsing the
        # HandlerEnvironment.json, but we are in a bash script here,
        # so assume it's at ../config/.
        config_dir=$(readlink -f "${SCRIPT_DIR}/../config")
        status_dir=$(readlink -f "${SCRIPT_DIR}/../status")
        config_file=$(ls $config_dir | grep -E ^[0-9]+.settings$ | sort -n | tail -n 1)
        if [ -f "$config_file" ]; then
            echo "Cannot locate the config file.">&2
            exit 1
        fi
        status_file=$(echo $config_file | sed s/settings/status/)
        readlink -f "$status_dir/$status_file"
}

write_status() {
	status_file="$(status_file_path)"
	if [ -f "$status_file" ]; then
		echo "Not writing a placeholder status file, already exists: $status_file"
	else
		echo "Writing a placeholder status file indicating progress before forking: $status_file"
		timestamp="$(date --utc --iso-8601=seconds)"
		cat > "$status_file" <<- EOF
			[
				{
					"version": 1,
					"timestampUTC": "$timestamp",
					"status": {
						"operation": "Enable",
						"status": "transitioning",
						"formattedMessage": {
							"lang": "en",
							"message": "Enable in progress"
						}
					}
				}
			]
		EOF
	fi
}


if [ "$#" -ne 1 ]; then
    echo "Incorrect usage."
    echo "Usage: $0 <command>"
    exit 1
fi

# Redirect logs of the handler process
mkdir -p "$LOG_DIR"
exec &> >(tee -ia "$LOG_DIR/$LOG_FILE")

# Start handling the process in the background
bin="$(readlink -f "$SCRIPT_DIR/$HANDLER_BIN")"
cmd="$1"

# For commands other than 'enable', execute the handler process as a child process
commandToExecute="$bin $cmd"

if [[ "$cmd" == "enable" ]]; then
    # for 'enable' command, write a .status file first, then double fork
    # to detach from the  handler process tree to avoid getting terminated 
    # after the 15-minute extension enabling timeout.
    # & will execute the binary on the background and will not block current shell execution
    write_status
    commandToExecute="nohup '$bin' '$cmd' &"
fi

### Retry logic to check if RunCommand binary is open for write and execute the command
set -e
retry_attempts=0

set -x

if command -v fuser&>/dev/null; then
    while (( retry_attempts < 10 )); do
        # Use fuser to detect if the run command binary is open for write to help detect potential conflicts like 'text file busy' errors that prevents execution of Run Command binary.
        fuser_output=$(fuser -vw "$bin" 2>&1)
        fuser_status=$?
        fuser_output=$(fuser -v "$bin" 2>&1)
        fuser_return_code=$?

        # Use 10 retries with 3 seconds sleep between retries to allow for any potential conflicts to resolve before executing the Run Command binary.
        if [ "$fuser_return_code" -eq 0 ]; then
            echo "Custom script binary $bin is open for write. Users with write access:"
            echo "$fuser_output"
            echo "Binary is open for write. Allowing execution via best-effort path after all retries have been exhausted..."
            ((++retry_attempts))
            echo "sleeping for 3 seconds before retry, attempt ${retry_attempts} of 10"
            sleep 3
            continue
        elif [ "$fuser_return_code" -eq 1 ]; then
            echo "No users have write access to $bin. Proceeding with execution."
            break
        else
            echo "$fuser_output"
            echo "Unexpected Fuser error with return code $fuser_return_code while checking if $bin is open for write.using fuser command. Proceeding with best-effort execution..."
            break
        fi
    done
else
    echo "INFO: Not an error. fuser command not found. Install 'psmic' package to use fuser for checking if the Run Command binary is open for write to detect potential conflicts like 'text file busy' errors while executing Run Command binary. Proceeding with best-effort execution..."
fi
### End of retry logic

echo "Starting custom-script-handler..."
$commandToExecute
echo "custom-script-handler finished."
set +x

set -e