sudo: true
services:
 - docker
language: go
go: go1.7
install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo bash -
  - sudo apt-get install -qqy nodejs
  - sudo npm install -g npm
  - sudo npm install -g azure-cli
  - go get -u github.com/golang/lint/golint
  - go get -u github.com/ahmetalpbalkan/govvv
before_script:
  - docker version
  - docker info
  - azure telemetry --disable && azure -v
script:
  - test -z "$(gofmt -s -l -w $(find . -type f -name '*.go' -not -path './vendor/*') | tee /dev/stderr)"
  - test -z "$(golint . | tee /dev/stderr)"
  - test -z "$(go vet -v $(go list ./... | grep -v '/vendor/') | tee /dev/stderr)"
  - go list ./... | grep -v '/vendor/' | xargs go test -v -cover
  - make binary
  - bats integration-test/test
